version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wikigraph
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - '50005:5432'
    restart: always

  rabbitmq:
    image: 'bitnami/rabbitmq:3.9.14'
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: 123456
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq-data:/bitnami'

volumes:
  postgres-data:
  rabbitmq-data: